In [ ]:
%pip install torch==2.4.0
%pip install torchview==0.2.4


In [1]:
import torch
from torch import nn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from torchview import draw_graph
import numpy as np

np.random.seed(42)
torch.manual_seed(42)

c:\Users\Sabiha\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [3]:
from torch.optim import SGD

In [4]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
df=pd.read_csv('C:\\Users\\Sabiha\\Desktop\\Codes\\ML\\penguins_size.csv')
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

species: penguin species (Chinstrap, Adélie, or Gentoo)

culmen_length_mm: culmen length (mm)

culmen_depth_mm: culmen depth (mm)

flipper_length_mm: flipper length (mm)

body_mass_g: body mass (g)

island: island name (Dream, Torgersen, or Biscoe) in the Palmer Archipelago (Antarctica)

sex: penguin sex


In [6]:
count_na=df.isna().sum()
count_na

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [7]:
df.shape

(344, 7)

In [8]:
df.dropna(inplace=True)
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
4  Adelie  Torgersen              36.7             19.3              193.0   
5  Adelie  Torgersen              39.3             20.6              190.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
4       3450.0  FEMALE  
5       3650.0    MALE

In [9]:
df.dtypes

species               object
island                object
culmen_length_mm     float64
culmen_depth_mm      float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [10]:
X=df.drop(['species','island','sex'],axis=1).copy()
X.head()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0              39.1             18.7              181.0       3750.0
1              39.5             17.4              186.0       3800.0
2              40.3             18.0              195.0       3250.0
4              36.7             19.3              193.0       3450.0
5              39.3             20.6              190.0       3650.0

In [11]:
y=df['species'].copy()
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [12]:
df['species'].value_counts()

species
Adelie       146
Gentoo       120
Chinstrap     68
Name: count, dtype: int64

In [13]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,stratify=y)

In [20]:
values,counts=np.unique(y_train,return_counts=True)
counts=counts/np.sum(counts)
print(values,counts)

[0 1 2] [0.436 0.204 0.36 ]


In [21]:
values,counts=np.unique(y_test,return_counts=True)
counts=counts/np.sum(counts)
print(values,counts)

[0 1 2] [0.44047619 0.20238095 0.35714286]


In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
np.mean(X_train)

1.3100631690576846e-16

In [25]:
np.std(X_train)

1.0

In [26]:

# Convert to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)  # Long type for classification
y_test = torch.tensor(y_test, dtype=torch.long)

In [27]:
# Define the neural network model
class PenguinClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(PenguinClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size) 

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)  # No activation (CrossEntropyLoss applies softmax)
        return x

In [28]:
# Model parameters
input_size = X_train.shape[1]  # 4 features
hidden_size = 8  # Hidden layer neurons
output_size = 3  # 3 classes 

# Create model
model = PenguinClassifier(input_size, hidden_size, output_size)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()  # For multi-class classification
optimizer = SGD(model.parameters(), lr=0.01)

In [ ]:
# Training loop
num_epochs = 500
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")


Epoch [100/1500], Loss: 0.1242
Epoch [200/1500], Loss: 0.1134
Epoch [300/1500], Loss: 0.1043
Epoch [400/1500], Loss: 0.0964
Epoch [500/1500], Loss: 0.0897
Epoch [600/1500], Loss: 0.0839
Epoch [700/1500], Loss: 0.0788
Epoch [800/1500], Loss: 0.0743
Epoch [900/1500], Loss: 0.0704
Epoch [1000/1500], Loss: 0.0668
Epoch [1100/1500], Loss: 0.0637
Epoch [1200/1500], Loss: 0.0609
Epoch [1300/1500], Loss: 0.0584
Epoch [1400/1500], Loss: 0.0560
Epoch [1500/1500], Loss: 0.0540


In [35]:
# Evaluate model
with torch.no_grad():
    y_pred = model(X_test)
    _, predicted = torch.max(y_pred, 1)  # Get predicted class
    accuracy = (predicted == y_test).sum().item() / y_test.size(0)
    print(f"Test Accuracy: {accuracy * 100:.2f}%")



Test Accuracy: 100.00%


torch.max(outputs, 1) returns two values:

_: Maximum values (not required),thus not stored.

predicted: Indices of the maximum values along dimension 1 (which correspond to class labels with the highest probability).

<p>
>>> a = torch.randn(4, 4)<br>
>>> a<br>
tensor([[-1.2360, -0.2942, -0.1222,  0.8475],<br>
        [ 1.1949, -1.1127, -2.2379, -0.6702],<br>
        [ 1.5717, -0.9207,  0.1297, -1.8768],<br>
        [-0.6172,  1.0036, -0.6060, -0.2432]])<br>
>>> torch.max(a, 1)<br>
torch.return_types.max(values=tensor([0.8475, 1.1949, 1.5717, 1.0036]), indices=tensor([3, 0, 0, 1]))<br>
</p>

In [32]:
print(y_pred)

tensor([[ 0.7059,  1.1585, -1.0473],
        [-1.9151, -1.4913,  4.4873],
        [ 2.5407, -0.0990, -1.6123],
        [-0.7873, -1.2733,  2.6808],
        [-0.2790,  2.3136, -1.0207],
        [-1.0806, -0.6745,  2.5857],
        [-1.8638, -1.4246,  4.3564],
        [-0.2013,  2.3648, -1.1952],
        [-0.9089, -1.3513,  2.8421],
        [-1.2569, -1.1187,  3.1948],
        [ 3.4683, -0.4742, -1.9428],
        [-1.7566, -1.4500,  4.2191],
        [ 1.2334,  1.2628, -1.5896],
        [ 2.4095,  0.5875, -2.0660],
        [ 2.3421,  0.5447, -1.9843],
        [ 0.2149,  1.6376, -1.0582],
        [-1.1723, -0.9525,  2.9316],
        [ 3.8549, -0.6945, -2.2718],
        [ 1.6442,  0.8103, -1.5886],
        [ 2.9521,  0.0477, -2.1193],
        [-1.4173, -1.7100,  3.8925],
        [ 0.6451,  1.3207, -1.1637],
        [ 3.8459, -0.4876, -2.3204],
        [ 2.5960, -0.2520, -1.6291],
        [ 2.2800,  0.3303, -1.8342],
        [ 3.2088, -0.3540, -1.9317],
        [-1.0623, -0.9086,  2.7256],
 

In [33]:
model.eval()

PenguinClassifier(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)